server:
  port: 8082
  
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/microservices
    username: root
    password: 1709
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: RATING-SERVICE

  jpa: 
    hibernate:
      ddl-auto: update
    show_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka