server:
  port: 8087
  
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/microservices
    username: root
    password: 1709
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: HOTEL-SERVICE
  jpa: 
    hibernate:
      ddl-auto: update
    show_sql: true
  config:
    import: configserver:http://localhost:8088

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8762/eureka